---
abstract: 'wrap git(7) command-line interface'
author:
  - 'Hans Dieter Pearcey <hdp@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Git-Wrapper
no_index:
  directory:
    - inc
    - t
requires:
  File::pushd: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.006
