---
abstract: 'wrap git(7) command-line interface'
author:
  - 'Hans Dieter Pearcey <hdp@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.73'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Git-Wrapper
no_index:
  directory:
    - inc
    - t
requires:
  File::pushd: 0
version: 0.004
